name: fcd
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=0_gnu
  - ca-certificates=2019.11.28=hecc5488_0
  - certifi=2019.11.28=py37hc8dfbb8_1
  - cudatoolkit=10.1.243=h6bb024c_0
  - freetype=2.10.1=he06d7ca_0
  - intel-openmp=2020.0=166
  - jpeg=9c=h14c3975_1001
  - ld_impl_linux-64=2.34=h53a641e_0
  - libblas=3.8.0=14_openblas
  - libcblas=3.8.0=14_openblas
  - libffi=3.2.1=he1b5a44_1007
  - libgcc-ng=9.2.0=h24d8f2e_2
  - libgfortran-ng=7.3.0=hdf63c60_5
  - libgomp=9.2.0=h24d8f2e_2
  - liblapack=3.8.0=14_openblas
  - libopenblas=0.3.7=h5ec1e0e_6
  - libpng=1.6.37=hed695b0_1
  - libstdcxx-ng=9.2.0=hdf63c60_2
  - libtiff=4.1.0=hc7e4089_6
  - libwebp-base=1.1.0=h516909a_3
  - lz4-c=1.8.3=he1b5a44_1001
  - mkl=2020.0=166
  - ncurses=6.1=hf484d3e_1002
  - ninja=1.10.0=hc9558a2_0
  - olefile=0.46=py_0
  - openssl=1.1.1f=h516909a_0
  - pip=20.0.2=py_2
  - python=3.7.6=h8356626_5_cpython
  - python_abi=3.7=1_cp37m
  - pytorch=1.4.0=py3.7_cuda10.1.243_cudnn7.6.3_0
  - readline=8.0=hf8c457e_0
  - setuptools=46.1.3=py37hc8dfbb8_0
  - six=1.14.0=py_1
  - sqlite=3.30.1=hcee41ef_0
  - tk=8.6.10=hed695b0_0
  - torchvision=0.5.0=py37_cu101
  - wheel=0.34.2=py_1
  - xz=5.2.4=h516909a_1002
  - zlib=1.2.11=h516909a_1006
  - zstd=1.4.4=h3b9ef0a_2
  - pip:
    - absl-py==0.9.0
    - affine==2.3.0
    - albumentations==0.4.5
    - attrs==19.3.0
    - cachetools==4.0.0
    - chardet==3.0.4
    - click==7.1.1
    - click-plugins==1.1.1
    - cligj==0.5.0
    - cycler==0.10.0
    - decorator==4.4.2
    - efficientnet-pytorch==0.6.3
    - google-auth==1.12.0
    - google-auth-oauthlib==0.4.1
    - grpcio==1.27.2
    - idna==2.9
    - imagecodecs==2020.2.18
    - imageio==2.8.0
    - imgaug==0.2.6
    - joblib==0.14.1
    - kiwisolver==1.2.0
    - markdown==3.2.1
    - matplotlib==3.2.1
    - munch==2.5.0
    - networkx==2.4
    - numpy==1.18.2
    - oauthlib==3.1.0
    - opencv-python==4.2.0.32
    - pillow==7.1.0
    - pretrainedmodels==0.7.4
    - protobuf==3.11.3
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyparsing==2.4.6
    - python-dateutil==2.8.1
    - pywavelets==1.1.1
    - pyyaml==5.3.1
    - rasterio==1.1.3
    - requests==2.23.0
    - requests-oauthlib==1.3.0
    - rsa==4.0
    - scikit-image==0.16.2
    - scikit-learn==0.22.2.post1
    - scipy==1.4.1
    - segmentation-models-pytorch==0.1.0
    - sklearn==0.0
    - snuggs==1.4.7
    - tensorboard==2.2.0
    - tensorboard-plugin-wit==1.6.0.post2
    - tifffile==2020.2.16
    - tqdm==4.44.1
    - urllib3==1.25.8
    - werkzeug==1.0.1
prefix: /home/jnyborg/miniconda3/envs/fcd

